# Header
menu:
  Home: /
  Archives: /archives
  Read: /read
  About: /about
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- links
# - mathjax
# - recent_posts


# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Links
links:
  哔哩哔哩: http://www.bilibili.com
  基佬Fun: http://www.acfun.tv
  # 微博: http://weibo.com/bpsend/
mathjax: true
# 版权声明
show_declare: true
